### ISSUE TITLE
dynamic theme with custom icon

### ISSUE THREAD

**Issue by BanhMi939** [zzzribas/Patterns#1]
please, when you made a tutorial for creating dynamic theme, please add how to made the icon to round like this one. 
![image](https://user-images.githubusercontent.com/106416065/218266077-31a80662-8a33-4f40-8f92-89e166fe6156.png)

**Comment by zzzribas** [comment]
Hey! You can change that value in the ResidentMenu.szs.

Its the RdtBtnIconGame.Bflyt, P_IconGame.

![image](https://user-images.githubusercontent.com/93286561/220427978-380bff78-0abf-4275-805b-f0dba65b595b.png)

You may also need to change P_InnerCursor so it matches the Cursor.

Change this values to ones to your liking (more equals rounder.)
